@startuml
[*] --> broadcaster
rx --> [*]
FFxx --> FFkp
FFxx --> AMPxz
AMPxz --> FFbq
AMPxz --> FFgr
AMPxz --> FFsj
AMPxz --> FFrv
AMPxz --> AMPzf
FFpt --> FFvx
broadcaster --> FFfb
broadcaster --> FFxk
broadcaster --> FFgr
broadcaster --> FFvj
FFtz --> FFrz
FFlv --> FFzk
FFlz --> FFqn
FFhx --> AMPbz
FFqc --> FFkh
FFqc --> AMPbz
FFmj --> AMPjj
FFmj --> FFlv
FFqn --> FFvh
FFqn --> AMPjj
FFqq --> FFpt
FFqq --> AMPgf
FFqv --> FFxr
FFqv --> AMPjj
FFmt --> FFsj
FFmt --> AMPxz
AMPqx --> AMPgh
FFmx --> FFmt
FFmx --> AMPxz
AMPzf --> AMPgh
FFzk --> AMPjj
FFzk --> FFxv
FFrd --> FFcp
FFvh --> FFgx
FFvj --> FFhb
FFvj --> AMPjj
FFvm --> AMPbz
FFvm --> FFxh
AMPrk --> AMPgh
FFvp --> AMPxz
FFvp --> FFxx
FFrm --> AMPbz
FFrm --> FFxq
FFfb --> AMPbz
FFfb --> FFtg
FFnj --> AMPxz
AMPjj --> FFhb
AMPjj --> FFlz
AMPjj --> AMPrk
AMPjj --> FFxv
AMPjj --> FFvj
AMPjj --> FFvh
AMPjj --> FFlv
FFrr --> FFrv
FFrr --> AMPxz
FFvx --> AMPgf
FFvx --> FFcv
FFjm --> FFvm
FFjm --> AMPbz
FFrv --> FFmx
FFrz --> FFqq
FFrz --> AMPgf
FFbq --> FFrr
FFsj --> FFvp
FFkb --> AMPgf
AMPbz --> AMPqx
AMPbz --> FFcq
AMPbz --> FFxh
AMPbz --> FFfb
AMPbz --> FFtg
FFkh --> FFtp
FFkh --> AMPbz
AMPgf --> FFtz
AMPgf --> AMPcd
AMPgf --> FFrd
AMPgf --> FFxk
AMPgf --> FFpt
AMPgf --> FFcp
AMPgf --> FFgg
FFgg --> FFkn
AMPgh --> rx
AMPcd --> AMPgh
FFkn --> AMPgf
FFkn --> FFtz
FFkp --> AMPxz
FFkp --> FFnj
FFxb --> AMPxz
FFxb --> FFbq
FFgr --> AMPxz
FFgr --> FFxb
FFcp --> FFgg
FFcq --> FFjm
FFxh --> FFqc
FFgx --> AMPjj
FFgx --> FFqv
FFtg --> FFcq
FFxk --> AMPgf
FFxk --> FFrd
FFcv --> AMPgf
FFcv --> FFkb
FFxq --> AMPbz
FFxq --> FFhx
FFhb --> FFmj
FFxr --> AMPjj
FFtp --> FFrm
FFtp --> AMPbz
FFxv --> FFlz
@enduml
